# most things are kept in separate config files. i like to keep this file as sparse as possible.
default_config:

tts:
  - platform: google_translate

# we're pulling in a custom openzwave config for proper
# zooz zen25 support.
zwave:
  usb_path: /dev/ttyACM0
  config_path: /config/openzwave_config
  device_config_glob: !include zwave_device_config.yaml

zha:
  usb_path: /dev/ttyUSB1

homeassistant:
  # devices that require a lot of configuration are in packages just for easier readability.
  packages: !include_dir_named packages

# homeassistant themes - these need to be updated
# because they don't seem to work with the new entity
# page.
frontend:
  themes: !include_dir_merge_named theme

# custom zones like work, so homeassistant
# can track where i am as a named location. 
zone:
  - name: Work
    icon: mdi:account-tie
    latitude: !secret office_lat
    longitude: !secret office_long
    radius: 200

light: !include light.yaml

# enable auto discovery
discovery:

# using dark sky for weather
weather:
  - platform: darksky
    api_key: !secret darksky_apikey 
    mode: daily

# google calendar
google:
  client_id: !secret google_client_id 
  client_secret: !secret google_client_secret 

# turn off lights when house is empty - requires sun 
# device_sun_light_trigger:
# sun:

ifttt:
  key: !secret ifttt_key

# by default, recorder saves to an sqlite file on disk
# if you've got a decent number of devices, this lags out
# rpi hard. moved to a mysql db on a different rpi.
# changing recorder to send to usb disk instead
recorder:
  db_url: !secret mysql_uri
  purge_keep_days: 90
  exclude:
    domains:
      - automation
      - script
      - scene
      - zwave

# edit lovelace in yaml mode
lovelace:
  mode: yaml

sonos:
  media_player:
    hosts:
      - !secret sonos_bedroom
      - !secret sonos_loft
      - !secret sonos_living_room

mqtt:
  discovery: false
  broker: !secret mqtt_host
  port: !secret mqtt_port
  client_id: homeassistant
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/loft/status'
    payload: 'online'
  will_message:
    topic: 'hass/loft/status'
    payload: 'offline'

mqtt_eventstream:
  publish_topic: luke/loft
  subscribe_topic: master/topic
  ignore_event:
    - call_service
#    - state_changed

#mqtt_statestream:
#  base_topic: haloft
#  publish_attributes: true
#  publish_timestamps: true

notify:
  - platform: discord
    name: discord
    token: !secret discord_token
