title: Natural Born Fraggers
resources:
  - type: js
    url: /local/cards/calendar-card.js
  - type: js
    url: /local/cards/button-entity-row.js
  - type: js
    url: /local/cards/light-entity-row.js
  - type: js
    url: /local/cards/light-entity-card.js
  - type: module
    url: /local/cards/circle-sensor-card.js
  - type: js
    url: /local/cards/flex-table-card.js
  - type: js
    url: /local/cards/tiles-card.js
  - type: module
    url: /local/cards/weather-card/weather-card.js
  - type: module
    url: /local/cards/mini-graph-card-bundle.js
  - type: js
    url: /local/cards/monster-card.js
  - type: js
    url: /local/cards/button-card.js
  - type: js
    url: /local/cards/mini-media-player-bundle.js
  - type: js
    url: /local/cards/swipe-card.js
  - type: js
    url: /local/cards/battery-entity.js
  - type: module
    url: /local/cards/hass-aarlo.js
views: 
  - !include /config/lovelace/views/home.yaml
  - !include /config/lovelace/views/binary_sensor.yaml
  - !include /config/lovelace/views/sensor.yaml
  - !include /config/lovelace/views/light.yaml
  - !include /config/lovelace/views/switch.yaml
