---

binary_sensor:
  - platform: template
    sensors:
      guest_bedroom_plug:
        value_template: "{{ is_state('switch.guest_bedroom_zen25_s2', 'on') }}"
      guest_bedroom_plug_left:
        value_template: "{{ is_state('switch.guest_bedroom_zen25_s2_left', 'on') }}"
      guest_bedroom_plug_right:
        value_template: "{{ is_state('switch.guest_bedroom_zen25_s2_right', 'on') }}"
      guest_bedroom_plug_usb:
        value_template: "{{ is_state('switch.guest_bedroom_zen25_s2_usb', 'on') }}"
      living_room_plug:
        value_template: "{{ is_state('switch.living_room_zen25_s2', 'on') }}"
      living_room_plug_left:
        value_template: "{{ is_state('switch.living_room_zen25_s2_left', 'on') }}"
      living_room_plug_right:
        value_template: "{{ is_state('switch.living_room_zen25_s2_right', 'on') }}"
      living_room_plug_usb:
        value_template: "{{ is_state('switch.living_room_zen25_s2_usb', 'on') }}"

homeassistant:
  customize:
    # plug
    binary_sensor.guest_bedroom_plug:
      device_class: plug
      friendly_name: Guest Bedroom Plug
    binary_sensor.guest_bedroom_plug_left:
      device_class: plug
      friendly_name: Guest Bedroom Left Plug
    binary_sensor.guest_bedroom_plug_right:
      device_class: plug
      friendly_name: Guest Bedroom Right Plug
    binary_sensor.guest_bedroom_plug_usb:
      device_class: plug
      friendly_name: Guest Bedroom USB Plug
    binary_sensor.living_room_plug:
      device_class: plug
      friendly_name: Living Room Plug
    binary_sensor.living_room_plug_left:
      device_class: plug
      friendly_name: Living Room Left Plug
    binary_sensor.living_room_plug_right:
      device_class: plug
      friendly_name: Living Room Right Plug
    binary_sensor.living_room_plug_usb:
      device_class: plug
      friendly_name: Living Room USB Plug

    # power
    sensor.guest_bedroom_zen25_s2_power:
      device_class: power
      unit_of_measurement: W
    sensor.guest_bedroom_zen25_s2_left_power:
      device_class: power
      unit_of_measurement: W
    sensor.guest_bedroom_zen25_s2_right_power:
      device_class: power
      unit_of_measurement: W
    sensor.living_room_zen25_s2_power:
      device_class: power
      unit_of_measurement: W
    sensor.living_room_zen25_s2_left_power:
      device_class: power
      unit_of_measurement: W
    sensor.living_room_zen25_s2_right_power:
      device_class: power
      unit_of_measurement: W