automation:
  # if there is motion in the hallway
  # and the currently occupied room is bathroom, bedroom, or living room
  # the hallway is occupied 
  - alias: occupancy_hallway_1
    trigger:
      - platform: state
        entity_id: binary_sensor.hallway_3325
        to: 'on'
    condition:
      - condition: or
        conditions:
          - condition: state
            entity_id: input_select.occupied
            state: 'bathroom'
          - condition: state
            entity_id: input_select.occupied
            state: 'bedroom'
          - condition: state
            entity_id: input_select.occupied
            state: 'living_room'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.occupied
          option: hallway

  # if the washing machine door opens
  # the hallway is occupied
  - alias: occupancy_hallway_2
    trigger:
      - platform: state
        entity_id: binary_sensor.washing_machine
        to: 'open'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.occupied
          option: hallway

  # if the front door opens
  # the hallway is occupied
  - alias: occupancy_hallway_3
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door
        to: 'open'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.occupied
          option: hallway
