automation:
  # if there is motion in the kitchen
  # and the dining room is not active,
  # and the dining room is currently occupied
  # the kitchen is occupied.
  - alias: occupancy_kitchen_1
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_zse40_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.samjin_22ce0901_motion
        state: 'off'
      - condition: state
        entity_id: input_select.occupied
        state: 'dining_room'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.occupied
          option: kitchen

  # if the dining room motion turns off
  # and the kitchen motion is on
  # the kitchen is occupied.
  - alias: occupancy_kitchen_2
    trigger:
      - platform: state
        entity_id: binary_sensor.samjin_22ce0901_motion
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.kitchen_zse40_motion
        state: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.occupied
          option: kitchen

  # if the kitchen entrance sensor turns on
  # and the kitchen motion sensor is on
  # and the dining room is currently occupied
  # the kitchen is occupied.
  - alias: occupancy_kitchen_3
    trigger:
      - platform: state
        entity_id: binary_sensor.samjin_65260901_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: binary_sensor.kitchen_zse40_motion
        state: 'on'
      - condition: state
        entity_id: input_select.occupied
        state: 'dining_room'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.occupied
          option: kitchen