#
# in_bed is set by my withings sleep sensor and ifttt.
#
# this automation is mostly going to be run by saying 'good morning' to alexa,
# but if the sun is up and the bedroom door opens while we're out of bed, it
# will automatically trigger. 
#
# this is two automations instead of one just so we have the option of disabling 
# the automatic part without disabling the sleeping switch in alexa.
#

- alias: good morning
  trigger:
    - platform: state
      entity_id: input_boolean.in_bed
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.bedroom_door
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: binary_sensor.bedroom_door
      state: 'on'
    - condition: state
      entity_id: input_boolean.in_bed
      state: 'off'
  action:
    - service: script.wake_up


- alias: good morning (manual)
  trigger:
    - platform: state
      entity_id: input_boolean.sleeping
      from: 'on'
      to: 'off'
  action:
    - service: script.wake_up