#
# in_bed is set by my withings sleep sensor and ifttt.
#
# after getting in bed, run sleep automations if the bedroom door
# is closed. verify that our status isn't asleep already, becauuse there
# is no need to run the automation twice if i get up in the middle of the
# night.
#
# todo: add conditions for
#  - if laptop is pingable at the end of those 5 minutes
#  - if media is playing on the bedroom apple tv
#
# todo: split this up to a sleep mode and a napping mode
# this can be determined by if the sun is above/below horizon.
#

- alias: good night
  trigger:
    platform: state
    entity_id: input_boolean.in_bed
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.bedroom_door
      state: 'off'
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    - service: script.go_to_sleep