##############################################
########## bathroom motion lighting ##########
##############################################

# turn bathroom lights at 
# - 100% during the day
# - 50% at night
# - a single bulb for 1% while sleeping
# only do this when lights are off so it doesn't overwrite manual settings.
- alias: bathroom lights
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.motion_lights
      state: 'on'
    - condition: state
      entity_id: light.bathroom
      state: 'off'
  action:
    service: light.turn_on
    data_template:
      brightness_pct: >-
        {% if is_state("input_boolean.sleeping", "on") %}
          1
        {% elif is_state("sun.sun", "below_horizon") %}
          50
        {% elif is_state("sun.sun", "above_horizon") %}
          100
        {% else %}
          25
        {% endif %}
      entity_id: 
        - >- 
          {% if is_state("input_boolean.sleeping", "on") %}
            light.bathroom_mirror_1
          {% else %}
            light.bathroom
          {% endif %}

# turn off bathroom lights when no motion detected and the door is open
# - 1 minute during the day
# - 5 minutes at night 
# - 1 minute when sleeping mode is on
- alias: bathroom lights off
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_motion
    from: 'on'
    to: 'off'
    for:
      minutes: ->
        {% if is_state("input_boolean.sleeping", "on") %}
          1
        {% elif is_state("sun.sun", "below_horizon") %}
          5
        {% elif is_state("sun.sun", "above_horizon") %}
          1
        {% else %}
          2
        {% endif %}
  condition:
    - condition: state
      entity_id: input_boolean.motion_lights
      state: 'on'
    - condition: state
      entity_id: light.bathroom
      state: 'on'
    - condition: state
      entity_id: binary_sensor.bathroom_door
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.bathroom


#############################################
########## kitchen motion lighting ##########
#############################################

# turn kitchen lights at 
# - 100% during the day
# - 50% at night
# - never while sleeping
# only do this when lights are off so it doesn't overwrite manual settings.
# technically, we only haver a 100% mode for kitchen, but the lightstrip will
# be added soon.
- alias: kitchen lights
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.motion_lights
      state: 'on'
    - condition: state
      entity_id: light.kitchen_lights
      state: 'off'
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    service: light.turn_on
    data_template:
      brightness_pct: >-
        {% if is_state("sun.sun", "below_horizon") %}
          50
        {% elif is_state("sun.sun", "above_horizon") %}
          100
        {% else %}
          25
        {% endif %}
      entity_id: light.kitchen_lights

# turn off kitchen lights when no motion detected
# - 2 minute during the day
# - 5 minutes at night 
- alias: kitchen lights off
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion
    from: 'on'
    to: 'off'
    for:
      minutes: ->
        {% if is_state("sun.sun", "below_horizon") %}
          5
        {% elif is_state("sun.sun", "above_horizon") %}
          2
        {% else %}
          2
        {% endif %}
  condition:
    - condition: state
      entity_id: input_boolean.motion_lights
      state: 'on'
    - condition: state
      entity_id: light.kitchen_lights
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.kitchen_lights


#################################################
########## dining room motion lighting ##########
#################################################

# turn on lights:
# - kitchen + dining - 100% during the day
# - dining - 50% at night
# - never while sleeping
# only do this when lights are off so it doesn't overwrite manual settings.
# technically, we only haver a 100% mode for kitchen, but the lightstrip will
# be added soon.
- alias: dining room lights
  trigger:
    platform: state
    entity_id: binary_sensor.dining_room_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.motion_lights
      state: 'on'
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    - service: light.turn_on
      data_template:
        brightness_pct: >-
          {% if is_state("sun.sun", "below_horizon") %}
            50
          {% elif is_state("sun.sun", "above_horizon") %}
            100
          {% else %}
            25
          {% endif %}
        entity_id:
          - light.dining_room
          - >-
            {% if is_state("sun.sun", "above_horizon") %}
              light.kitchen_lights
            {% endif %}
      
# turn off dining room & kitchen lights when no motion detected
# - 5 minute during the day
# - 2 minutes at night 
- alias: dining room lights off
  trigger:
    platform: state
    entity_id: binary_sensor.dining_room_motion
    from: 'on'
    to: 'off'
    for:
      minutes: >-
        {% if is_state("sun.sun", "above_horizon") %}
          5
        {% else %}
          2
        {% endif %}
  condition:
    - condition: state
      entity_id: input_boolean.motion_lights
      state: 'on'
  action:
    service: light.turn_off
    data:
      entity_id: 
        - light.kitchen_lights
        - light.dining_room


#############################################
########## hallway motion lighting ##########
#############################################

# turn hallway lights at 
# - 100% during the day
# - 75% at night
# only do this when lights are off so it doesn't overwrite manual settings.
- alias: hallway lights
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_motion
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.motion_lights
      state: 'on'
    - condition: state
      entity_id: light.hallway
      state: 'off'
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
  action:
    service: light.turn_on
    data_template:
      brightness_pct: >-
        {% if is_state("sun.sun", "below_horizon") %}
          75
        {% elif is_state("sun.sun", "above_horizon") %}
          100
        {% else %}
          25
        {% endif %}
      entity_id: light.hallway

# turn off hallway lights when no motion detected in 1 minute
- alias: hallway lights off
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_motion
    from: 'on'
    to: 'off'
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: input_boolean.motion_lights
      state: 'on'
    - condition: state
      entity_id: light.hallway
      state: 'on'
  action:
    service: light.turn_off
    entity_id: light.hallway
